- name: Create bastion host
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/vpc_setup
    - vars/vpc_variables
    - vars/Bastion_setup
  tasks:
    - name: Create Key Pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: key_pair

    - name: Save Private Key to File
      copy:
        content: "{{ key_pair.private_key }}"
        dest: "./bastion-keypair.pem"
        mode: "0600"
      when: key_pair.changed

    - name: Create security group for instance
      ec2_group:
        name: "{{ sg_name }}"
        vpc_id: "{{ vpcout }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: sg_out

    - name: Display security group ID
      debug:
        var: sg_out.group_id
      
    - name: Provision a new bastion host instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ bastion_ami }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ pub1_out }}"
        assign_public_ip: yes
        group_id: "{{ sg_out.group_id }}"
        count: 1
        instance_tags:
          Name: "{{ bastion_name }}"
      register: bastion_instance