- name: Create bastion host
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars/vpc_setup
    - vars/vpc_variables
    - vars/Bastion_setup
  tasks:
    - name: Create Key Pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: key_pair

    - name: Save Private Key to File
      copy:
        content: "{{ key_pair.private_key }}"
        dest: "./bastion-keypair.pem"
        mode: "0600"
    - name: Create bastion Security Group
      