---
- name: Create a new VPC in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/vpc_setup

  tasks:
    - name: Create a new VPC
      ec2_vpc_net:
        state: "{{ state }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        name: "{{ vpc_name }}"
        resource_tags:
          Name: "{{ vpc_name }}"
      register: vpcout

    - name: Create public subnets
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        resource_tags:
          Name:  vp-pubsub1
      register: pub1_out

    - name: Create public subnets
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub2Cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        resource_tags:
          Name:  vp-pubsub2
      register: pub2_out

    - name: Create private subnets
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub1Cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        resource_tags:
          Name:  vp-privsub1
      register: priv1_out

    - name: Create private subnets
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub2Cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        resource_tags:
          Name:  vp-privsub2
      register: priv2_out

    - name: Create an Internet Gateway
      ec2_vpc_igw:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: my-igw
      register: igw_out
      