---
- name: Create a new VPC in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/vpc_setup

  tasks:
    - name: Create a new VPC
      ec2_vpc_net:
        state: "{{ state }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        name: "{{ vpc_name }}"
        resource_tags:
          Name: "{{ vpc_name }}"
      register: vpcout

    - name: Create public subnets
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        resource_tags:
          Name:  vp-pubsub1
      register: pub1_out